FROM {{ item.image }}

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Update and install Python and necessary tools
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Reset the frontend variable
ENV DEBIAN_FRONTEND=
