---

galaxy_info:
  author: Ian Falatik
  description: Role to install PowerShell
  license: GNU General Public License v3.0
  min_ansible_version: "2.14.0"
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
        - "buster"
    - name: Fedora
      versions:
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
        - "32"
        - "33"
        - "34"
    - name: Ubuntu
      versions:
        - "jammy"
        - "focal"
        - "bionic"
  galaxy_tags:
    - powershell
    - install
dependencies: []
