---

# https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine
- name: Assert a correct version is selected
  assert:
    that:
      - install_powershell_version_alpine in ['7.4.1', '7.3.11', '7.2.18']
    fail_msg: "The version of PowerShell to install on Alpine Linux must be one of the following: 7.4.1, 7.3.11, 7.2.18"
    success_msg: "The version of PowerShell to install on Alpine Linux is valid"

- name: Install requirements
  community.general.apk:
    name: "ca-certificates, less, ncurses-terminfo-base, krb5-libs, libgcc, libintl, libssl1.1, libstdc++, tzdata, userspace-rcu, zlib, icu-libs, tar"
    state: present
    no_cache: true
  become: true

- name: Install requirements
  community.general.apk:
    name: "lttng-ust"
    state: present
    repository: "https://dl-cdn.alpinelinux.org/alpine/edge/main"
    no_cache: true
  become: true

- name: Download release archive
  ansible.builtin.get_url:
    url: "https://github.com/PowerShell/PowerShell/releases/download/v{{ install_powershell_version_alpine }}\
      /powershell-{{ install_powershell_version_alpine }}-linux-musl-x64.tar.gz"
    dest: "/tmp/powershell-{{ install_powershell_version_alpine }}-linux-musl-x64.tar.gz"
    mode: '0644'
  become: true
  delegate_to: localhost

- name: Create PowerShell directory
  ansible.builtin.file:
    path: "/opt/microsoft/powershell/7"
    state: directory
    mode: "0755"
  become: true

- name: Extract release archive
  ansible.builtin.unarchive:
    src: "/tmp/powershell-{{ install_powershell_version_alpine }}-linux-musl-x64.tar.gz"
    dest: "/opt/microsoft/powershell/7"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Make pwsh executable
  ansible.builtin.file:
    path: "/opt/microsoft/powershell/7/pwsh"
    mode: "0755"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create symlink to /usr/bin/pwsh
  ansible.builtin.file:
    path: "/usr/bin/pwsh"
    state: link
    src: "/opt/microsoft/powershell/7/pwsh"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

...
