---

- name: Add Microsoft repository key
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm"
    state: present
  become: true

- name: Install powershell
  ansible.builtin.yum:
    name: "powershell"
    state: present
    update_cache: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

...
