name: GHA for ifalatik.powershell

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml
  integration:
    uses: ansible-network/github_actions/.github/workflows/integration_simple.yml@main
    with:
      # defaults from https://github.com/ansible-network/github_actions/blob/main/.github/workflows/integration_simple.yml
      # exclude `devel`
      matrix_exclude: >-
        [
          {
            "ansible-version": "stable-2.13",
            "python-version": "3.11"
          },
          {
            "ansible-version": "stable-2.16",
            "python-version": "3.9"
          },
          {
            "ansible-version": "milestone",
            "python-version": "3.9"
          },
          {
            "ansible-version": "devel",
            "python-version": "3.9"
          },
          {
            "ansible-version": "devel",
            "python-version": "3.10"
          },
          {
            "ansible-version": "devel",
            "python-version": "3.11"
          }
        ]
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
  unit-galaxy:
    uses: ansible-network/github_actions/.github/workflows/unit_galaxy.yml@main

  all_green:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - integration
      - sanity
      - unit-galaxy
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.integration.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}'
          ]) == {'success'}"
